# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bee58a61d624d238c9c7269a30849d6ca45c06347393d87edb5b73933d80ea65a36302b36f6f03bcab8e50908dcbda5141bd3ce59bbc3d14886f37f95fec527d

test:
  secret_key_base: 74cee6e1d622fb95e979c222325b26f974b5d959ee6611e142c9d28919e6abc782a99a028049030b8705c3cfc649b50ae6b6a6305ee953e673f70dd87bab85f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
